import type { Metadata } from 'next';
import './globals.css';
import { Container } from '@/components/Container';
import { Header } from '@/components/Header';

export const metadata: Metadata = {
  title: {
    default: 'The Blog - Este é um blog em Next.js',
    template: ' %s | The Blog',
  },
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang='pt-BR'>
      <body>
        <Container>
          <Header />

          {children}

          <footer className='text-center text-6xl font-bold py-8'>
            Rodape
          </footer>
        </Container>
      </body>
    </html>
  );
}
